### ISSUE TITLE
Video feed - FPV view - UI Widget

### ISSUE THREAD

**Issue by Djacob502** [dji-sdk/Android-Bridge-App#2]
When using the UI library FPV widget - there is no video feed The screen is blank.  The FPV widget works just fine without using the Android bridge app. 
As an update, I'm working on a project to analyze the video feed. It would be very helpful to have the bridge work with the video feed. In this case I'm using the texture view/surface view and not the FPV widget to display the video.

**Comment by talobin** [comment]
@Djacob502 
With the new version 1.2.0 and SDK 4.4.0, this issue has been fixed.
Please check it out.
Thanks!

**Comment by Djacob502** [comment]
Thanks!
