### ISSUE TITLE
iOS cross compatibility

### ISSUE THREAD

**Issue by dallinski** [dji-sdk/Android-Bridge-App#3]
Any chance this will be modified so that iOS devices can be connected wirelessly to the Android device acting as bridge?

**Comment by oliverou** [comment]
Hi @dallinski , currently, the Android Bridge app doesn't support with iOS Devices.

**Comment by talobin** [comment]
@dallinski 
The latest Bridge (1.2.0) can be used with iOS SDK.
It can take multiple connections at once and each can be from a different platform.
Thanks!
