### ISSUE TITLE
Release APK is not available

### ISSUE THREAD

**Issue by ConnerHansen** [dji-sdk/Android-Bridge-App#5]
Earlier releases provided an APK for easy installation on an android device. The APKs have been removed, requiring me to build these releases from scratch in order to update. Please provide a release APK rather than just the source files.

**Comment by talobin** [comment]
@ConnerHansen APKs are available in the release section
https://github.com/dji-sdk/Android-Bridge-App/releases

**Comment by ConnerHansen** [comment]
That's where they were. I only see two links for v1.2.0; a zip file and a tarball, both of which only contain the source code. Both tags and releases have the same links.

**Comment by talobin** [comment]
I have just released 1.2.1 with APK file in it.
Please try again.
Thanks.
