### ISSUE TITLE
IP Address not correct

### ISSUE THREAD

**Issue by Jai-GAY** [dji-sdk/Android-Bridge-App#8]
i have 2 Android phones (HTC 4.3 and Sony Z5 6.0.1) and both phone displayed a different IP address connected to identical WiFi spot.

HTC 172. 30.xxxx.xx identical to [Speedtest by Ookla IP address displayed](https://play.google.com/store/apps/details?id=org.zwanoo.android.speedtest&hl=en)
Sony Z5 10.108.69.80 **NOT** identical to Speedtest by Ookla

May i know why ?
Android-Bridge-App version 1.2.4
Android Studio 3.1.3

**Comment by Jai-GAY** [comment]
the solution needs to know Mobile connection or Wifi connection can't use Utils.getIPAddress() for both.
[example here](https://itekblog.com/android-get-mobile-ip-address/).

and with just only Mobile data connection, the IP address is also wrong (why i don't know).

**Comment by alainpimentel** [comment]
@Jai-GAY the Bridge app is only supported using Wifi connection.
However, it is expected to display the correct local ip if connected to a Wifi. 
I'll verify the local ip address with a couple devices and Speedtest to see what's wrong.

**Comment by alainpimentel** [comment]
After investigating, it appears that the Bridge app works as expected when connected to wifi or ethernet. We don't expect this to work when connected to mobile data. 
I'm updating the documentation to make this clear.

**Comment by petered** [comment]
Yep - just ran into this and @alainpimentel 's answer solved it.

I needed to *Turn off Mobile data* on the phone connected to the remote controller, then *restart the bridge app* - it then gives you a different IP, which you enter in the `onRegister` callback with 

```
                   ...
                    Log.i(ConnectionActivity.TAG, "onRegister: Registration Successful")
                    val bridge_ip = "192.168.0.119" // Or whatever appears on device
                    DJISDKManager.getInstance().enableBridgeModeWithBridgeAppIP(bridge_ip)
```
